CI-CD workflow and terraform file updated

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -20,18 +20,165 @@ permissions:
   contents: read
 
 jobs:
-  CI:
-    runs-on: ubuntu-latest
+    setup:
+      runs-on: ubuntu-latest
+      steps:
+        - name: Checkout Code
+          uses: actions/checkout@v4
+  
+        - name: Set up Terraform
+          uses: hashicorp/setup-terraform@v3
 
-    steps:
-      # Checkout code from the repository
-      - name: 'Checkout code'
-        uses: 'actions/checkout@v2'
+        # Build trust between GitHub and AWS using OIDC connector
+        - name: configure aws credentials
+          uses: aws-actions/configure-aws-credentials@v3
+          with:
+              role-to-assume: ${{ secrets.AWS_IAM_ARN }}
+              role-session-name: samplesession
+              aws-region: ${{ secrets.AWS_REGION }}
 
-      # Build trust between GitHub and AWS using OIDC connector
-      - name: configure aws credentials
-        uses: aws-actions/configure-aws-credentials@v3
-        with:
-           role-to-assume: ${{ secrets.AWS_IAM_ARN }}
-           role-session-name: samplesession
-           aws-region: ${{ secrets.AWS_REGION }}
+        - name: Terraform init 
+          run: terraform init
+
+        - name: Terraform Validate 
+          run: terraform validate
+            
+
+    apply:
+      runs-on: ubuntu-latest
+      needs: setup
+      if: |
+        (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply') ||
+        (github.event_name == 'push' && !contains(github.event.head_commit.message, 'destroy'))
+      steps:
+        - name: Checkout Code
+          uses: actions/checkout@v4
+  
+        - name: Set up Terraform
+          uses: hashicorp/setup-terraform@v3
+  
+        - name: configure aws credentials
+          uses: aws-actions/configure-aws-credentials@v3
+          with:
+              role-to-assume: ${{ secrets.AWS_IAM_ARN }}
+              role-session-name: samplesession
+              aws-region: ${{ secrets.AWS_REGION }}
+
+        - name: Terraform Init
+          run: terraform init
+
+        - name: Terraform Plan
+          run: terraform plan -out=tfplan 
+
+        - name: Terraform Apply
+          run: terraform apply -auto-approve 
+            
+    post_apply:
+      runs-on: ubuntu-latest
+      needs: apply
+      if: success()
+      steps:
+        - name: Checkout Code
+          uses: actions/checkout@v4
+  
+        - name: Set up Terraform
+          uses: hashicorp/setup-terraform@v3
+  
+        - name: Configure AWS Credentials
+          uses: aws-actions/configure-aws-credentials@v4
+          with:
+            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+            aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
+  
+        - name: Retrieve Terraform Outputs
+          id: tf_outputs
+          run: |
+            echo "Retrieving Terraform Outputs..."
+            echo "INSTANCE_PUBLIC_IP=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV
+  
+        - name: Add GitHub Runner IP to Security Group
+          run: |
+            RUNNER_IP=$(curl -s https://checkip.amazonaws.com)
+            echo "Runner IP: $RUNNER_IP"
+            aws ec2 authorize-security-group-ingress \
+              --group-id "${{ env.SECURITY_GROUP_ID }}" \
+              --protocol tcp \
+              --port 22 \
+              --cidr "$RUNNER_IP/32" || echo "Failed to add rule to EC2 Security Group"
+
+        - name: Wait for Security Group to Update
+          run: sleep 12
+
+        # Create known_hosts file inside SSH directory 
+        - name: Create SSH directory and known_hosts file
+          run: |
+            mkdir -p ~/.ssh
+            touch ~/.ssh/known_hosts
+
+        # Add private key to id_rsa
+        - name: Extract SSH private key    
+          run: echo "${{ secrets.PRIVATE_SSH_KEY }}" > ~/.ssh/id_rsa
+          shell: bash
+
+        # Grant read-write permission to id_rsa 
+        - name: Set proper permissions for the private key   
+          run: chmod 600 ~/.ssh/id_rsa
+
+        # Install SSH Client
+        - name: Install SSH Client    
+          run: sudo apt-get install -y openssh-client
+          
+        # Build trust between GitHub and AWS using OIDC connector
+        - name: configure aws credentials
+          uses: aws-actions/configure-aws-credentials@v3
+          with:
+            role-to-assume: ${{ secrets.AWS_IAM_ARN }}
+            role-session-name: samplerolesession
+            aws-region: ${{ secrets.AWS_REGION }}
+          
+        # Pulling image from ECR and deploying on EC2 which contains docker
+        - name: Deploy to EC2 with Docker   # In this step we are deploying our application on EC2 instance
+          run: |
+            ssh-keyscan -H ${{ secrets.INSTANCE_PUBLIC_IP }} >> ~/.ssh/known_hosts
+            ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.INSTANCE_PUBLIC_IP }} '
+              dnf update -y
+              
+              dnf install -y amazon-linux-extras
+              amazon-linux-extras enable java-openjdk17
+              dnf install -y \
+                  yum-utils \
+                  apt-transport-https \
+                  ca-certificates \
+                  curl \
+                  openjdk-17-jre \
+                  gcc \
+                  kernel-devel-$(uname -r)
+              
+              aws s3 cp --recursive s3://ec2-linux-nvidia-drivers/latest/ .
+              chmod +x NVIDIA-Linux-x86_64*.run
+              /bin/sh ./NVIDIA-Linux-x86_64*.run --tmpdir . --silent
+              
+              echo "options nvidia NVreg_EnableGpuFirmware=0" | tee --append /etc/modprobe.d/nvidia.conf
+              
+              dnf install -y docker
+              usermod -aG docker ec2-user
+              systemctl enable --now docker
+              
+              distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
+              curl -s -L https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo | tee /etc/yum.repos.d/nvidia-container-toolkit.repo
+              dnf install -y nvidia-container-toolkit
+              nvidia-ctk runtime configure --runtime=docker
+              systemctl restart docker
+              
+              docker run -d --gpus=all -v ollama:/root/.ollama -p 11434:11434 --name ollama --restart always ollama/ollama
+              sleep 120
+              
+              docker exec ollama ollama run deepseek-r1:7b
+              docker exec ollama ollama run deepseek-r1:14b
+              
+              docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main
+            '
+
+
+      
